[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "py-ai"
version = "0.1.0"
description = "i think i made ai..."
authors = [{ name="Theobobble" }]
dependencies = []
