[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "template"
version = "0.1.0"
description = "template"
authors = [{ name="Theobobble" }]
dependencies = []
